export const DASHBOARD_TEXT = {
  admin: {
    title: "PANEL DE ADMINISTRACIÓN",
    metrics: {
      activeUsers: {
        title: "Usuarios activos",
        value: "120",
        change: "+12.5%",
        period: "esta semana",
        increasing: true,
      },
      retentionRate: {
        title: "Tasa de Retención",
        value: "87%",
        change: "+2.5%",
        period: "vs mes anterior",
        increasing: true,
      },
      activeQuizzes: {
        title: "Cuestionarios Activos",
        value: "40",
        change: "+90%",
        period: "Tasa de finalización",
        increasing: true,
      },
      lorem: {
        title: "Certificados Entregados",
        value: "100",
        change: "22.5%",
        period: "esta semana",
        increasing: true,
      },
    },
    charts: {
      trends: {
        title: "Lorem",
        dateRange: "May 30 - Abr 30",
        series: ["Lorem", "Lorem B"],
      },
      roleDistribution: {
        title: "Distribución de Roles",
        roles: {
          mentors: {
            label: "Mentores",
            percentage: 35,
            color: "#a155b9",
          },
          juniors: {
            label: "Juniors",
            percentage: 50,
            color: "#7987ff",
          },
          companies: {
            label: "Empresas",
            percentage: 15,
            color: "#f765a3",
          },
        },
      },
    },
    questionnaires: {
      title: "Gestión de Cuestionarios",
      searchPlaceholder: "Buscar",
      addButtonText: "Agregar Cuestionario",
      columns: {
        name: "Nombre",
        lastUpdate: "Última Actualización",
        questions: "Preguntas",
        role: "Rol",
      },
      data: [
        {
          id: 1,
          name: "Encuesta 1 - Habilidades blandas importancia",
          lastUpdate: "10/03/2023",
          questions: 5,
          role: "Junior",
        },
        {
          id: 2,
          name: "Encuesta 2 - Mejora en la Comunicación",
          lastUpdate: "10/03/2023",
          questions: 10,
          role: "Mentor",
        },
        {
          id: 3,
          name: "Encuesta 3 - Estrategias de Comunicación",
          lastUpdate: "10/03/2023",
          questions: 5,
          role: "Starup",
        },
        {
          id: 4,
          name: "Encuesta 4 - Optimización de la Comunicación",
          lastUpdate: "10/03/2023",
          questions: 6,
          role: "Junior",
        },
        {
          id: 5,
          name: "Encuesta 5 - Comunicación Efectiva",
          lastUpdate: "10/03/2023",
          questions: 9,
          role: "Junior",
        },
        {
          id: 6,
          name: "Encuesta 6 - Análisis de Comunicación",
          lastUpdate: "10/03/2023",
          questions: 10,
          role: "Junior",
        },
      ],
    },
    users: {
      title: "Gestión de Usuarios",
      searchPlaceholder: "Search",
      addButtonText: "Lorem",
      data: [
        {
          id: 1,
          avatar: "/placeholder.svg?height=40&width=40",
          nombre: "Musharof",
          apellido: "Chowdhury",
          nickname: "Randy",
          email: "randy123@gmail.com",
          rol: "Junior",
          estado: "Activo",
        },
        {
          id: 2,
          avatar: "/placeholder.svg?height=40&width=40",
          nombre: "Nenifer",
          apellido: "Lofess",
          nickname: "Lofers",
          email: "lofers2023@gmail.com",
          rol: "Mentor",
          estado: "Activo",
        },
        {
          id: 3,
          avatar: "/placeholder.svg?height=40&width=40",
          nombre: "Jhon",
          apellido: "Smith",
          nickname: "Smurff",
          email: "smurff.world@gmail.com",
          rol: "Startup",
          estado: "Activo",
        },
        {
          id: 4,
          avatar: "/placeholder.svg?height=40&width=40",
          nombre: "Sulium",
          apellido: "Keliym",
          nickname: "Sulemi_0",
          email: "sulemi0@example.com",
          rol: "Junior",
          estado: "Pendiente",
        },
        {
          id: 5,
          avatar: "/placeholder.svg?height=40&width=40",
          nombre: "Alex",
          apellido: "Semuyel",
          nickname: "Kassian1",
          email: "kassian.one@gmail.com",
          rol: "Mentor",
          estado: "Pendiente",
        },
        {
          id: 6,
          avatar: "/placeholder.svg?height=40&width=40",
          nombre: "Humil",
          apellido: "Limition",
          nickname: "Edu",
          email: "edu.learning@gmail.com",
          rol: "Mentor",
          estado: "Danger",
        },
      ],
    },
  },
  navigation: {
    inicio: "Inicio",
    ranking: "Ranking",
    lorem: "Lorem",
    perfil: "Perfil",
  },
};
